# -*- coding: utf-8 -*-
"""my_learning_prompt_chaining.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BhJcYCljh8aSQ4oKEQ8Itut0xVetKxg7
"""

!pip install google-genai -q

from google import genai
import os
from google.colab import userdata
os.environ["GEMINI_API_KEY"]=userdata.get('gemini')

MODEL_NAME = "gemini-2.5-flash"
client=genai.Client()

def outline(userprompt):
  response_outline=client.models.generate_content(model=MODEL_NAME,
    contents=f"Make an outline (3 bullet points) for a short blog post about {userprompt}.")

  return response_outline.text

def expand(outline_res):
  expand_response=client.models.generate_content(model=MODEL_NAME,
    contents=f"Expand each point into 2-3 sentences:\n{outline_res}")

  return expand_response.text

def conclusion(expand_respons):
  conclusion_response=client.models.generate_content(model=MODEL_NAME ,
                            contents=f"Write a short conclusion for this blog post on SQL basics.{expand_respons}")

  return conclusion_response.text

def function(user_input):
  a=outline(user_input)
  print(f"this is outline \n {a}")
  print
  b=expand(a)
  print(f"this is expand \n {b}")
  c=conclusion(b)
  print(f"this is conclusion \n {c}")

user=input("enter your prompt")
function(user)