# -*- coding: utf-8 -*-
"""orchesterator_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wLaOq4y_K2fTAc0y6untpSuEfF5aNPJC
"""

import os
from google import genai
from google.colab import userdata
import asyncio
from google.genai import types

os.environ["GEMINI_API_KEY"] = userdata.get("gemini")
client = genai.Client()

async def orchestrator(task):
    # The correct path for async calls is client.aio.models.generate_content
    # We also pass the config to ensure the instruction is applied.
    config = types.GenerateContentConfig(
        system_instruction="Break this task into exactly 3 subtasks. Write each subtask on a separate line. Do not include numbers, bullet points, or markdown asterisks."
    )

    response = await client.aio.models.generate_content(
        model="gemini-2.0-flash",
        contents=task,
        config=config
    )

    steps = response.text.split("\n")
    return [s.strip(" .* ") for s in steps if s.strip()][:3]

async def worker(subtask):
  response_worker=client.aio.models.generate_content(model="gemini-2.5-flash",
        contents=f"Do this subtask in 3–4 sentences: {subtask}")
  return response_worker.text

async def synthesizer(results: list):
    joined = "\n\n".join(results)
    response = await client.aio.models.generate_content(
        model="gemini-2.5-flash",
        contents=f"Combine these into a single short comprehensive guide:\n{joined}",
        config=types.GenerateContentConfig(temperature=0.4)
    )
    return response.text

import time

async def orchestrator_worker(task: str):
    # الخطوة 1: نطلب من المايسترو تقسيم المهمة
    subtasks = await orchestrator(task)
    print("🤖 SUBTASKS GENERATED BY GEMINI:", subtasks, "\n")

    # الخطوة 2: تشغيل العمال بالتوازي لتنفيذ المهام الفرعية
    results = await asyncio.gather(*(worker(s) for s in subtasks))

    # الخطوة 3: دمج وتلخيص النتائج كلها في دليل نهائي
    final = await synthesizer(results)
    return final

# --- التشغيل مع معالجة أخطاء تجاوز الحصص (Quota Handling) ---
async def run_with_retry(task):
    for attempt in range(3):
        try:
            answer = await orchestrator_worker(task)
            print("\n✨ FINAL ANSWER:\n", answer)
            break
        except Exception as e:
            if "429" in str(e):
                wait_time = (attempt + 1) * 30
                print(f"⚠️ Quota reached. Retrying in {wait_time}s... (Attempt {attempt+1}/3)")
                await asyncio.sleep(wait_time)
            else:
                raise e

await run_with_retry("Write a short beginner guide to SQL")