# -*- coding: utf-8 -*-
"""parallization methode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16tjVY46S1axVPqJpfxJlaVavS1QCVxvk
"""

import os
import asyncio
from google import genai
from google.colab import userdata


os.environ["GEMINI_API_KEY"] = userdata.get("gemini")

client=genai.Client()

async def ask(role, instruction) :
    """استدعاء جيمني بشكل غير متزامن بالتوازي"""

    # لاحظ استخدام client.aio بدل client العادية للـ Async
    response = await client.aio.models.generate_content(
        model="gemini-2.5-flash",
        contents=instruction,
        # بنحط الـ Role جوة الـ system_instruction في جيمني عشان يتقمص الشخصية صح
        config={'system_instruction': f"You are a helpful {role}."}
    )
    return response.text
async def parallization(user_request):

  tasks = [
        ask("Researcher", f"List 5 key beginner topics for: {user_request}"),
        ask("Curator", f"Suggest 3 free online resources for: {user_request}"),
        ask("Planner", f"Make a 3-day study plan for: {user_request}"),
      ]
  results = await asyncio.gather(*tasks)
  roles = ["Researcher", "Curator", "Planner"]
  final_answer = "\n\n".join([f"--- {r} ---\n{o}" for r, o in zip(roles, results)])
  return final_answer

# 3. تشغيل الكود
if __name__ == "__main__":
    answer = await parallization("learning SQL basics")
    print(answer)