# -*- coding: utf-8 -*-
"""Router design patteren.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DooxM0R1J45923370h2vqs2gU00JgDYN
"""

!pip install google-genai -q

from google import genai
import os
from google.colab import userdata
os.environ["GEMINI_API_KEY"] = userdata.get("gemini")

client=genai.Client()
def router(user_input):
 # Step 1: classify the input
    if user_input.lower().startswith("math:"):
        route = "math"
    elif user_input.lower().startswith("translate:"):
        route = "translate"
    else:
        route = "general"

    if route =="math":
      prompt=f"You are a math teacher. Solve clearly: {user_input}"
    elif route == "translate":
      text = user_input.split("translate:", 1)[1].strip()
      prompt = f"You are a translator. Translate this to Arabic: {text}"
    else:
      prompt = f"You are a creative writer. Answer: {user_input}"

    resp = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt
      )
    return resp.text

print(router("math: 2+2"))